export enum Languages {
  fr = 'Français',
  en = 'Anglais',
  es = 'Espagnol',
  de = 'Allemand',
  it = 'Italien',
  pt = 'Portugais',
  ru = 'Russe',
  zh = 'Chinois',
  ja = 'Japonais',
  ko = 'Coréen',
  ar = 'Arabe',
  nl = 'Néerlandais',
  sv = 'Suédois',
  no = 'Norvégien',
  da = 'Danois',
  fi = 'Finnois',
  pl = 'Polonais',
  cs = 'Tchèque',
  hu = 'Hongrois',
  tr = 'Turc'
}